In [ ]:
!pip install scikit-learn-intelex



Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 87 kB 2.8 MB/s 
     |████████████████████████████████| 26.1 MB 3.9 MB/s 
     |████████████████████████████████| 300.3 MB 20 kB/s 
     |████████████████████████████████| 4.0 MB 47.6 MB/s 


In [ ]:
import numpy as np
from sklearnex import patch_sklearn
patch_sklearn()

from sklearn.cluster import DBSCAN

X = np.array([[1., 2.], [2., 2.], [2., 3.],
            [8., 7.], [8., 8.], [25., 80.]], dtype=np.float32)
clustering = DBSCAN(eps=3, min_samples=2).fit(X)


Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)


In [ ]:
from numpy.lib.function_base import average
from re import U
from sklearn import tree
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
import pydot
import graphviz
import pandas as pd
import pydotplus
import collections
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import StandardScaler


from sklearn.preprocessing import MinMaxScaler
import numpy as np
from sklearn.datasets import make_regression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import validation_curve

from sklearn.impute import SimpleImputer

fileName = "/content/drive/MyDrive/Weather/weatherAUS.xlsx"

dataFrame= pd.read_excel(fileName,header=0, usecols="C,D,L,M,N,O,P,Q,T,U,V")

print(dataFrame.shape)

dataFrame=dataFrame.dropna(subset=['RainToday'])



x=dataFrame.drop(["RainToday"],axis=1)


y=dataFrame.RainToday
#y=y.to_numpy()
#y=np.ravel(y)


medianimputer = SimpleImputer(missing_values=np.nan, strategy='median')
x=medianimputer.fit_transform(x)



#print(type(x))

x=pd.DataFrame(x, columns = ['MinTemp','MaxTemp','WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',  'Pressure3pm', 'Temp9am' , 'Temp3pm'])
print(x)


dataFrame=pd.concat([x,y],axis=1)



#dataFrame.to_csv("mputed_hw_4_part_1.csv", index=True)



print(dataFrame)


dataFrame=dataFrame.dropna()



#**dataFrame.to_csv("imputed_hw_4_part_1.csv", index=True)

#trylinearfit(predictors.copy(), target, medianimputer)


(145460, 11)
        MinTemp  MaxTemp  WindSpeed9am  WindSpeed3pm  Humidity9am  \
0          13.4     22.9          20.0          24.0         71.0   
1           7.4     25.1           4.0          22.0         44.0   
2          12.9     25.7          19.0          26.0         38.0   
3           9.2     28.0          11.0           9.0         45.0   
4          17.5     32.3           7.0          20.0         82.0   
...         ...      ...           ...           ...          ...   
142194      2.8     23.4          13.0          11.0         51.0   
142195      3.6     25.3          13.0           9.0         56.0   
142196      5.4     26.9           9.0           9.0         53.0   
142197      7.8     27.0          13.0           7.0         51.0   
142198     14.9     22.6          17.0          17.0         62.0   

        Humidity3pm  Pressure9am  Pressure3pm  Temp9am  Temp3pm  
0              22.0       1007.7       1007.1     16.9     21.8  
1              25.0       

In [ ]:
x=dataFrame.drop(["RainToday"],axis=1)
scalerX = MinMaxScaler()
scalerX.fit(x)
x = scalerX.transform(x)
#*x=pd.DataFrame(x, columns = ['MinTemp','MaxTemp','WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',  'Pressure3pm', 'Temp9am' , 'Temp3pm'])

#df = pd.DataFrame(my_array, columns = ['Column_A','Column_B','Column_C'])

#print(type(x))
#print(x)

y=dataFrame.RainToday
#y=y.to_numpy()
y=np.ravel(y)



#*newdataframe=pd.concat([x,y],axis=1)

from imblearn.over_sampling import RandomOverSampler

ros=RandomOverSampler(random_state=42)
x_oversampled,y_oversampled=ros.fit_resample(x,y)

#con = np.concatenate((x,y))

x=pd.DataFrame(x_oversampled, columns = ['MinTemp','MaxTemp','WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm', 'Pressure9am',  'Pressure3pm', 'Temp9am' , 'Temp3pm'])
y=pd.DataFrame(y_oversampled, columns=['RainToday'])

newdataFrame=pd.concat([x,y],axis=1)



print(newdataFrame)

#*newdataFrame.to_csv("balanced_imputed_hw_4_part_1.csv", index=True)

#newdataframe=pd.dataFrame(data=con)

         MinTemp   MaxTemp  WindSpeed9am  WindSpeed3pm  Humidity9am  \
0       0.516509  0.517241      0.153846      0.275862         0.71   
1       0.375000  0.559387      0.030769      0.252874         0.44   
2       0.504717  0.570881      0.146154      0.298851         0.38   
3       0.417453  0.614943      0.084615      0.103448         0.45   
4       0.613208  0.697318      0.053846      0.229885         0.82   
...          ...       ...           ...           ...          ...   
215071  0.686321  0.553640      0.115385      0.195402         0.76   
215072  0.462264  0.703065      0.100000      0.252874         0.32   
215073  0.521226  0.605364      0.115385      0.321839         0.59   
215074  0.426887  0.335249      0.153846      0.195402         0.87   
215075  0.639151  0.626437      0.200000      0.298851         0.55   

        Humidity3pm  Pressure9am  Pressure3pm   Temp9am   Temp3pm RainToday  
0              0.22     0.449587       0.4800  0.506356  0.519305    

In [ ]:
from numpy.lib.function_base import average
from re import U
from sklearn import tree
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
import pydot
import graphviz
import pandas as pd
import pydotplus
import collections
import matplotlib.pyplot as plt
from sklearn.linear_model import SGDClassifier


from sklearn.preprocessing import MinMaxScaler
import numpy as np
from sklearn.datasets import make_regression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import validation_curve

from sklearn.impute import KNNImputer


from sklearn import metrics
from sklearn.metrics import accuracy_score


x=newdataFrame.drop(["RainToday"],axis=1)
x=x.to_numpy()
#x=x.to_numpy

print(type(x))
print(x)

y=newdataFrame.RainToday

y=y.to_numpy()
y=np.ravel(y)



print(y)




X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=42)

from sklearn.svm import SVC

model= SVC(kernel='rbf',probability=False, gamma=1, cache_size=800,tol=.01,C=100)

model.fit(X_train,y_train)


<class 'numpy.ndarray'>
[[0.51650943 0.51724138 0.15384615 ... 0.48       0.50635593 0.51930502]
 [0.375      0.55938697 0.03076923 ... 0.4912     0.51271186 0.56756757]
 [0.50471698 0.57088123 0.14615385 ... 0.5056     0.59322034 0.54633205]
 ...
 [0.52122642 0.60536398 0.11538462 ... 0.5424     0.58898305 0.62162162]
 [0.42688679 0.33524904 0.15384615 ... 0.64       0.36016949 0.33011583]
 [0.63915094 0.62643678 0.2        ... 0.6832     0.69915254 0.61969112]]
['No' 'No' 'No' ... 'Yes' 'Yes' 'Yes']


SVC(C=100, cache_size=800, gamma=1, tol=0.01)

In [ ]:


Ypred=model.predict(X_test)

print(model.score(X_test,y_test))


print ("Classification accuracy = %f" % metrics.accuracy_score(y_test, Ypred))


0.5309713940323837
Classification accuracy = 0.530971


In [ ]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV


parameters = {'C': [0.1,1,100], 'gamma': [1,0.1,0.01],'kernel': ['rbf']}
svc = svm.SVC()
clf = GridSearchCV(svc, parameters)
clf.fit(X_train, y_train)


GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 100], 'gamma': [1, 0.1, 0.01],
                         'kernel': ['rbf']})

In [ ]:
print(clf.best_params_)
print(clf.best_score_)

{'C': 100, 'gamma': 1, 'kernel': 'rbf'}
0.5332093455771243
